<?php
/**
 * Html to show the Transformation of Simple Product to Mytunes Product
 *
 * TODO: License
 *
 * @category   Que
 * @package    Que_Mytunes
 * @author     Steffen Mücke <mail@quellkunst.de>
 */
?>
<?php
    $_product = $this->getProduct();
?>
<div class="fieldset">
<p>
    <?php echo $this->__('mytunes_adminhtml_transform_product_type_notice') ?>
</p>
<table cellspacing="0" class="form-list">
    <tbody>
        <tr>
            <td class="label">
                <label for="mytunes_transform_newsku"><?php echo $this->__('New Mytunes Product Sku')?></label>
            </td>
            <td class="value">
                <input type="text" id="mytunes_transform_newsku" class="input-text" name="mytunes[transform][newsku]" value="<?php echo $_product->getSku() ?>">
                <input type="hidden" name="mytunes[transform][product_id]" value="<?php echo $_product->getId() ?>">
            </td>
        </tr>
        <tr>
            <td class="label">
                <label for="mytunes_transform_keepsimple"><?php echo $this->__('Keep Simple Product')?></label>
            </td>
            <td class="value">
                <?php echo $this->getKeepSimpleSelect() ?>
            </td>
        </tr>
        <tr>
            <td class="label"></td>
            <td class="value">
                <?php echo $this->getSubmitButton() ?>
            </td>
        </tr>
    </tbody>
</table>
</div>

<script type="text/javascript">
//<![CDATA[

var transform = new MytunesTransform('mytunes_transform_btn_submit', <?php echo $this->getTransformConfigJson() ?>);

if($('mytunes_transform_btn_submit')) {
    Event.observe('mytunes_transform_btn_submit', 'click', transform.submit.bind(transform));
}

//]]>
</script>