<?php
/**
 * html to show the Mytunes settings in the product edit page
 *
 * TODO: License
 *
 * @category   Que
 * @package    Que_Mytunes
 * @author     Steffen Mücke <mail@quellkunst.de>
 */
?>
<?php
    $_product = $this->getProduct();
    $_album = false;
    if ($_product->getId() != null) {
        $_album = $_product->getTypeInstance(true)->getAlbum($_product);
    }
?>
<div class="fieldset">
<table cellspacing="0" class="form-list">
    <tbody>
        <tr>
            <td class="label">
                <label for="mytunes_mytunes_enable_player"><?php echo $this->__('Enable Mytunes Player')?></label>
            </td>
            <td class="value">
                <input type="hidden" name="mytunes[album][album_id]" value="<?php echo $_album?$_album->getId():'' ?>" />
                <?php echo $this->getEnablePlayerSelect() ?>
            </td>
            <td class="scope-label">
            <?php if (!Mage::app()->isSingleStoreMode()): ?>
                [STORE VIEW]
            <?php endif; ?>
            </td>
            <td class="value use-default">
            <?php if($_product->getStoreId()): ?>
                <input id="mytunes_mytunes_enable_player_default" type="checkbox" name="use_default[]" value="mytunes_enable_player" onclick="toggleValueElements(this, this.parentNode.parentNode)" />
                <label class="normal" for="mytunes_mytunes_enable_player_default">Use Default Value</label>
            <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td class="label"><label for="mytunes_mytunes_enable_downloads"><?php echo $this->__('Enable Downloads')?></label>
            </td>
            <td class="value">
                <?php echo $this->getEnableDownloadsSelect() ?>
            </td>
            <td class="scope-label">
            <?php if (!Mage::app()->isSingleStoreMode()): ?>
                [STORE VIEW]
            <?php endif; ?>
            </td>
            <td class="value use-default">
            <?php if($_product->getStoreId()): ?>
                <input id="mytunes_mytunes_enable_downloads_default" type="checkbox" name="use_default[]" value="mytunes_enable_downloads" onclick="toggleValueElements(this, this.parentNode.parentNode)" />
                <label class="normal" for="mytunes_mytunes_enable_downloads_default">Use Default Value</label>
            <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td class="label"><label for="mytunes_mytunes_enable_albumdownload"><?php echo $this->__('Enable Download of complete Album')?></label>
            </td>
            <td class="value">
                <?php echo $this->getEnableAlbumdownloadSelect() ?>
            </td>
            <td class="scope-label">
            <?php if (!Mage::app()->isSingleStoreMode()): ?>
                [STORE VIEW]
            <?php endif; ?>
            </td>
            <td class="value use-default">
            <?php if($_product->getStoreId()): ?>
                <input id="mytunes_mytunes_enable_albumdownload_default" type="checkbox" name="use_default[]" value="mytunes_enable_albumdownload" onclick="toggleValueElements(this, this.parentNode.parentNode)" />
                <label class="normal" for="mytunes_mytunes_enable_albumdownload_default">Use Default Value</label>
            <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td class="label"><label for="mytunes_album_price"><?php echo $this->__('Price for complete Album Download')?> <span class="required">*</span></label>
            </td>
            <td class="value">
                <input type="text" id="mytunes_album_price" class="validate-zero-or-greater input-text" name="mytunes[album][price]" value="<?php echo Mage::helper('mytunes')->getFormattedPrice(($_album)? $_album->getPrice() : $this->getDefaultAlbumPrice()) ?>">
            </td>
            <td class="scope-label">[GLOBAL]</td>
            <td class="value use-default"></td>
        </tr>
    </tbody>
</table>
</div>